[build]
  functions = "api"
  publish = "."

[[redirects]]
  from = "/api/stalker"
  to = "/.netlify/functions/stalker"
  status = 200

[[redirects]]
  from = "/api/xtream/stream"
  to = "/.netlify/functions/xtream"
  status = 200

[[redirects]]
  from = "/api/m3u/fetch"
  to = "/.netlify/functions/parse"
  status = 200

[[redirects]]
  from = "/api/stream"
  to = "/.netlify/functions/stream"
  status = 200

[[redirects]]
  from = "/player/*"
  to = "/player.html"
  status = 200
